// lib/data.js — Velmique Maison de Parfum

/* HERO SLIDES — shape mirrors backend Slider model:
   { title, description, buttonText, image, ctaHref }.
   ctaHref maps to the slider's linked category on the backend. */
export const heroSlides = [
  {
    id: 'slide-1',
    title: 'A Scent To Remember',
    description: 'Hand-blended extraits built on Kannauj rose, aged oud and Kashmir saffron.',
    buttonText: 'Shop Velmique',
    image: '/perfumehero.png',
    ctaHref: '/shop',
  },
  {
    id: 'slide-2',
    title: 'Slow Distilled',
    description: 'Rose absolute, oud and Mysore sandalwood — composed by hand, aged for months.',
    buttonText: 'Discover Noir',
    image: '/perfumehero2.png',
    ctaHref: '/shop?collection=noir',
  },
  {
    id: 'slide-3',
    title: 'Golden Hour, Bottled',
    description: 'Tuberose, neroli and warm musk — radiance from desk to dinner.',
    buttonText: 'Explore Luminara',
    image: '/perfumehero3.png',
    ctaHref: '/shop?collection=luminara',
  },
];

export const products = [
  {
    id: '1',
    name: 'Noir Absolu',
    price: 24600,
    originalPrice: 32300,
    category: 'Eau de Parfum',
    collection: 'Noir',
    gender: 'Unisex',
    images: [
      'https://images.unsplash.com/photo-1610461888750-10bfc601b874?w=800&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=800&q=80&auto=format&fit=crop',
    ],
    description: 'A dark, magnetic composition of aged oud, smoked vetiver and midnight rose. Noir Absolu is the scent of power — worn by those who leave a room unforgettable.',
    details: ['Top: Black pepper, Bergamot', 'Heart: Kannauj rose, Assam oud', 'Base: Smoked vetiver, Ambergris', '50ml / 100ml', 'Concentration: Eau de Parfum'],
    sizes: ['30ml', '50ml', '100ml'],
    rating: 4.9,
    reviews: 248,
    badge: 'Sale',
    inStock: true,
    slug: 'noir-absolu',
  },
  {
    id: '2',
    name: 'Velvet Oud',
    price: 20800,
    category: 'Eau de Parfum',
    collection: 'Signature',
    gender: 'Men',
    images: [
      'https://images.unsplash.com/photo-1563170351-be82bc888aa4?w=800&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?w=800&q=80&auto=format&fit=crop',
    ],
    description: 'Rich Assam oud wrapped in velvety Mysore sandalwood and warm amber. A timeless oriental fragrance that deepens with every hour on skin — built for long evenings and longer memories.',
    details: ['Top: Saffron, Cardamom', 'Heart: Kannauj rose, Aged oud', 'Base: Mysore sandalwood, Amber, Musk', '50ml / 100ml', 'Concentration: Eau de Parfum'],
    sizes: ['30ml', '50ml', '100ml'],
    rating: 4.8,
    reviews: 189,
    badge: 'Bestseller',
    inStock: true,
    slug: 'velvet-oud',
  },
  {
    id: '3',
    name: 'Lumière Dorée',
    price: 16600,
    category: 'Eau de Parfum',
    collection: 'Luminara',
    gender: 'Women',
    images: [
      'https://images.unsplash.com/photo-1594035910387-fea47794261f?w=800&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1585386959984-a4155224a1ad?w=800&q=80&auto=format&fit=crop',
    ],
    description: 'A radiant floral-citrus inspired by golden afternoons. Tuberose, jasmine sambac and warm musk create an aura of effortless luminosity — light enough for office, lasting enough for dinner.',
    details: ['Top: Neroli, Bergamot, Mandarin', 'Heart: Tuberose, Jasmine sambac', 'Base: White musk, Cedarwood', '50ml / 100ml', 'Concentration: Eau de Parfum'],
    sizes: ['30ml', '50ml', '100ml'],
    rating: 4.7,
    reviews: 134,
    badge: 'New',
    inStock: true,
    slug: 'lumiere-doree',
  },
  {
    id: '4',
    name: 'Obsidian Rose',
    price: 18300,
    category: 'Eau de Parfum',
    collection: 'Signature',
    gender: 'Women',
    images: [
      'https://images.unsplash.com/photo-1615634260167-c8cdede054de?w=800&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1596451190630-186aff535bf2?w=800&q=80&auto=format&fit=crop',
    ],
    description: 'A modern rose reimagined — Kannauj rose absolute meets black pepper and patchouli. Dark, smoky and intoxicating, built to last from afternoon to afterparty.',
    details: ['Top: Black pepper, Pink grapefruit', 'Heart: Kannauj rose, Iris', 'Base: Patchouli, Oakmoss, Musk', '50ml / 100ml', 'Concentration: Eau de Parfum'],
    sizes: ['30ml', '50ml', '100ml'],
    rating: 4.6,
    reviews: 312,
    badge: 'Bestseller',
    inStock: true,
    slug: 'obsidian-rose',
  },
  {
    id: '5',
    name: 'Phantom Encens',
    price: 33600,
    category: 'Extrait de Parfum',
    collection: 'Noir',
    gender: 'Men',
    images: [
      'https://images.unsplash.com/photo-1615529162924-f8605388461d?w=800&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=800&q=80&auto=format&fit=crop',
    ],
    description: 'Our most intense extrait. Sacred frankincense, labdanum and dark woods compose a fragrance of rare depth — for the gallery opening, the wedding reception, the unforgettable night.',
    details: ['Top: Frankincense, Elemi', 'Heart: Labdanum, Cistus', 'Base: Dark woods, Benzoin, Vanilla', '50ml only', 'Concentration: Extrait de Parfum'],
    sizes: ['50ml'],
    rating: 4.9,
    reviews: 87,
    badge: 'Limited',
    inStock: true,
    slug: 'phantom-encens',
  },
  {
    id: '6',
    name: 'Lumière Blanche',
    price: 14000,
    originalPrice: 17900,
    category: 'Eau de Toilette',
    collection: 'Luminara',
    gender: 'Women',
    images: [
      'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=800&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1610461888750-10bfc601b874?w=800&q=80&auto=format&fit=crop',
    ],
    description: 'A clean, airy white floral — the scent of freshly starched cotton and morning-glory. Light, elegant and endlessly wearable through warm afternoons and humid evenings.',
    details: ['Top: Aldehydes, Peach', 'Heart: White lily, Magnolia', 'Base: White musk, Cashmere wood', '50ml / 100ml', 'Concentration: Eau de Toilette'],
    sizes: ['30ml', '50ml', '100ml'],
    rating: 4.5,
    reviews: 156,
    badge: 'Sale',
    inStock: true,
    slug: 'lumiere-blanche',
  },
  {
    id: '7',
    name: 'Céleste Ambre',
    price: 20000,
    category: 'Eau de Parfum',
    collection: 'Luminara',
    gender: 'Unisex',
    images: [
      'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=800&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1596451190630-186aff535bf2?w=800&q=80&auto=format&fit=crop',
    ],
    description: 'Warm amber and Madagascan vanilla entwined with exotic spices. Sensual, enveloping and resilient through long evenings — feels like a second skin you never want to wash off.',
    details: ['Top: Cinnamon, Clove', 'Heart: Amber, Benzoin', 'Base: Madagascan vanilla, Tonka bean, Musk', '50ml / 100ml', 'Concentration: Eau de Parfum'],
    sizes: ['30ml', '50ml', '100ml'],
    rating: 4.8,
    reviews: 203,
    badge: 'New',
    inStock: true,
    slug: 'celeste-ambre',
  },
  {
    id: '8',
    name: 'Sovereign Iris',
    price: 37800,
    category: 'Extrait de Parfum',
    collection: 'Signature',
    gender: 'Unisex',
    images: [
      'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=800&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1571781418606-70265b9cce90?w=800&q=80&auto=format&fit=crop',
    ],
    description: 'The pinnacle of Velmique artistry. Rare orris root from Florence aged for three years, anchored on Mysore sandalwood. Powdery, noble, utterly singular — limited to 500 bottles a year.',
    details: ['Top: Violet leaf, Aldehydes', 'Heart: Orris root, Iris pallida', 'Base: Vetiver, Mysore sandalwood, White musk', '50ml only', 'Concentration: Extrait de Parfum'],
    sizes: ['50ml'],
    rating: 5.0,
    reviews: 64,
    badge: 'Limited',
    inStock: true,
    slug: 'sovereign-iris',
  },
];

export const collections = [
  {
    id: '1',
    name: 'Noir',
    tagline: 'Darkness distilled',
    slug: 'noir',
    description: 'Dark, magnetic, deeply sensual. Built around aged oud and smoked vetiver — for those who command every room they enter.',
    image: 'https://images.unsplash.com/photo-1571781418606-70265b9cce90?w=800&q=80&auto=format&fit=crop',
    productCount: 8,
  },
  {
    id: '2',
    name: 'Signature',
    tagline: 'Your timeless mark',
    slug: 'signature',
    description: 'Timeless compositions that define the Velmique identity — refined, bold and unmistakable, built to travel everywhere with you.',
    image: 'https://images.unsplash.com/photo-1619994403073-2cec844b8e63?w=800&q=80&auto=format&fit=crop',
    productCount: 12,
  },
  {
    id: '3',
    name: 'Luminara',
    tagline: 'Radiance in a bottle',
    slug: 'luminara',
    description: 'Radiant, luminous scents built on tuberose, neroli and warm musks — golden hour bottled, made for daily wear.',
    image: 'https://images.unsplash.com/photo-1619994403073-2cec844b8e63?w=800&q=80&auto=format&fit=crop',
    productCount: 9,
  },
  {
    id: '4',
    name: 'Extrait',
    tagline: 'Pure concentration',
    slug: 'extrait',
    description: 'Our most concentrated, rare creations — high-extrait formulas built for collectors and connoisseurs who demand the extraordinary.',
    image: 'https://images.unsplash.com/photo-1547887538-e3a2f32cb1cc?w=800&q=80&auto=format&fit=crop',
    productCount: 5,
  },
  {
    id: '5',
    name: 'Tribute',
    tagline: 'Celebrate every milestone',
    slug: 'tribute',
    description: 'Fragrances composed as an ode to life\'s most meaningful moments — engagements, anniversaries, the pheras and the firsts.',
    image: 'https://images.unsplash.com/photo-1547887538-e3a2f32cb1cc?w=800&q=80&auto=format&fit=crop',
    productCount: 6,
  },
];

export const discoveryKits = [
  {
    id: 'dk1',
    name: 'Noir Discovery Kit',
    price: 7600,
    image: 'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=600&q=80&auto=format&fit=crop',
    slug: 'noir-discovery-kit',
    includes: '5 × 2ml samples · Free shipping',
  },
  {
    id: 'dk2',
    name: 'Luminara Discovery Kit',
    price: 7600,
    image: 'https://images.unsplash.com/photo-1563170351-be82bc888aa4?w=600&q=80&auto=format&fit=crop',
    slug: 'luminara-discovery-kit',
    includes: '5 × 2ml samples · Free shipping',
  },
];

export const shopTheLooks = [
  {
    id: 'stl1',
    image: 'https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?w=800&q=80&auto=format&fit=crop',
    products: ['Noir Absolu', 'Phantom Encens'],
    slugs: ['noir-absolu', 'phantom-encens'],
  },
  {
    id: 'stl2',
    image: 'https://images.unsplash.com/photo-1594035910387-fea47794261f?w=800&q=80&auto=format&fit=crop',
    products: ['Lumière Dorée', 'Obsidian Rose'],
    slugs: ['lumiere-doree', 'obsidian-rose'],
  },
];

export const blogPosts = [
  {
    id: '1',
    title: 'Wedding Season Fragrances: A Velmique Guide for Brides & Grooms',
    slug: 'wedding-season-fragrances',
    excerpt: 'From mehendi morning to the vidai — five extraits that hold their sillage from sunrise through the last function of the night.',
    content: '',
    image: 'https://images.unsplash.com/photo-1585386959984-a4155224a1ad?w=800&q=80&auto=format&fit=crop',
    author: 'Aanya Sharma',
    date: 'October 14, 2026',
    category: 'Guide',
    readTime: 6,
  },
  {
    id: '2',
    title: 'Behind the Bottle: How We Source Aged Oud',
    slug: 'sourcing-oud',
    excerpt: 'A look at how we work with sustainable agarwood farms in Hojai — and why aged oud is the soul of every Velmique extrait.',
    content: '',
    image: 'https://images.unsplash.com/photo-1615634260167-c8cdede054de?w=800&q=80&auto=format&fit=crop',
    author: 'Vikram Iyer',
    date: 'September 28, 2026',
    category: 'Brand',
    readTime: 8,
  },
  {
    id: '3',
    title: 'Festive Layering: Five Scents to Pair for the Season',
    slug: 'festive-fragrance-layering',
    excerpt: 'Lights, mithai and a signature trail to match. Our perfumer\'s pairings for the busiest, brightest fortnight of the year.',
    content: '',
    image: 'https://images.unsplash.com/photo-1587017539504-67cfbddac569?w=800&q=80&auto=format&fit=crop',
    author: 'Priya Mehra',
    date: 'October 22, 2026',
    category: 'Collections',
    readTime: 5,
  },
  {
    id: '4',
    title: 'Humidity-Proof: Make Your Fragrance Last Through the Wet Months',
    slug: 'humidity-fragrance-tips',
    excerpt: 'Heat and humidity are brutal on perfume. Our master perfumer shares five techniques to keep your sillage intact through monsoon.',
    content: '',
    image: 'https://images.unsplash.com/photo-1615529162924-f8605388461d?w=800&q=80&auto=format&fit=crop',
    author: 'Aanya Sharma',
    date: 'July 8, 2026',
    category: 'Guide',
    readTime: 4,
  },
];

export const testimonials = [
  {
    id: '1',
    name: 'Aanya Sharma',
    location: 'Mumbai',
    text: 'Noir Absolu is unlike anything I have ever worn. It evolves through the day — dark and mysterious in the morning, warm and sensual by evening.',
    rating: 5,
    product: 'Noir Absolu',
  },
  {
    id: '2',
    name: 'Vikram Iyer',
    location: 'Bengaluru',
    text: 'I wore Phantom Encens to four events this season and got compliments at every single one. Worth every rupee.',
    rating: 5,
    product: 'Phantom Encens',
  },
  {
    id: '3',
    name: 'Priya Mehra',
    location: 'New Delhi',
    text: 'Sovereign Iris is the most beautiful iris I have ever encountered. The depth and longevity are extraordinary — easily 12+ hours of wear.',
    rating: 5,
    product: 'Sovereign Iris',
  },
  {
    id: '4',
    name: 'Rohan Kapoor',
    location: 'Pune',
    text: 'Velvet Oud has become my signature scent. The Mysore sandalwood base is unmistakable — rich, complex and utterly addictive.',
    rating: 5,
    product: 'Velvet Oud',
  },
];

export const categories = ['All', 'Eau de Parfum', 'Extrait de Parfum', 'Eau de Toilette', 'Gift Sets', 'Discovery Sets'];
