const { DataTypes } = require('sequelize');
const { sequelize } = require('../config/db.js');

/**
 * AddressQualityScore — one row per unique shipping-address hash.
 *
 * Used by services/addressQualityService.calculateAddressQuality() to
 * decide whether COD should be offered for a given address. Score is
 * updated whenever a delivery for that address succeeds or fails so
 * the heuristic improves over time.
 *
 * The underlying table is created in setupDatabase.js as Migration 002
 * (predates this model file). We declare the same shape here so other
 * controllers can use Sequelize methods (findOne, increment, ...)
 * instead of raw SQL.
 */
const AddressQualityScore = sequelize.define('AddressQualityScore', {
  id: {
    type: DataTypes.INTEGER,
    primaryKey: true,
    autoIncrement: true,
  },
  // SHA-256 of (line1 | line2 | city | state | pincode) — generated by
  // addressQualityService.getAddressHash(). Unique per real-world
  // address, brand-independent (the same household may order across
  // brands and we want to share the reputation signal).
  address_hash: {
    type: DataTypes.STRING(64),
    allowNull: false,
    unique: true,
  },
  pincode: {
    type: DataTypes.STRING(10),
    allowNull: false,
  },
  // Latest computed score, 0-100. Recomputed on every order create
  // and overwritten here.
  quality_score: {
    type: DataTypes.INTEGER,
    allowNull: false,
    defaultValue: 50,
  },
  // Incremented on order status -> delivered.
  delivery_success_count: {
    type: DataTypes.INTEGER,
    allowNull: false,
    defaultValue: 0,
  },
  // Incremented on order status -> undelivered / rto / rto delivered.
  delivery_failure_count: {
    type: DataTypes.INTEGER,
    allowNull: false,
    defaultValue: 0,
  },
  last_updated: {
    type: DataTypes.DATE,
    defaultValue: DataTypes.NOW,
  },
}, {
  tableName: 'address_quality_scores',
  timestamps: true,
  createdAt: 'created_at',
  updatedAt: 'last_updated',
  indexes: [
    { fields: ['pincode'] },
    { fields: ['quality_score'] },
    { fields: ['address_hash'], unique: true },
  ],
});

module.exports = { AddressQualityScore };
